name: infowindow
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # cupertino_icons: ^0.1.3
  # flutter_polyline_points: ^0.1.0
  geocoder: ^0.2.1
  animate_icons: ^0.0.4 
  cloud_firestore: ^0.13.7
  provider: ^3.0.0
  google_maps_flutter: ^0.5.28+1
  flutter_google_places: ^0.2.6
  flutter_polyline_points: ^0.1.0
  geolocator: ^5.3.2+2
  # simple_slider: "^0.0.1"
  carousel_slider: ^2.2.1
  # carousel_pro: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true


  assets:
    - assets/destination_map_marker.png
    - assets/driving_pin.png
    - assets/friend1.jpg
    - assets/friend2.jpg
